# Generated by Django 5.0.6 on 2024-08-06 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogDetails',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('blog_title', models.CharField(max_length=50)),
                ('blog_desc', models.CharField(max_length=250)),
                ('blog_date', models.DateField()),
            ],
        ),
    ]
