# Generated by Django 5.0.7 on 2024-07-30 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetails',
            name='blog_description',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
